# Generated by Django 2.0.7 on 2018-07-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memo',
            options={'ordering': ['words'], 'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.AddField(
            model_name='memo',
            name='words',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memo',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='memo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
